import { Link } from "react-router-dom";
import { ArrowDownRight,ArrowRight,ArrowUpRight,CalendarDays,CircleDollarSign,Stethoscope,UsersRound } from "lucide-react";
import { initialAppointments } from "../../data/clinic";
const metrics=[
 [CalendarDays,"Citas hoy","12","+3 vs. ayer","blue"],[UsersRound,"Pacientes","438","+18 este mes","cyan"],[Stethoscope,"Tratamientos activos","73","8 por concluir","violet"],[CircleDollarSign,"Ingresos del mes","$184,300","+12.4%","green"]
];
export default function Dashboard(){return <><AdminHeader title="Buenos días, Ana" subtitle="Aquí tienes el resumen de la clínica para hoy."/><div className="admin-content"><section className="metric-grid">{metrics.map(([Icon,label,value,trend,tone])=><article className={`admin-metric ${tone}`} key={label}><span><Icon/></span><div><small>{label}</small><strong>{value}</strong><em className={trend.includes("concluir")?"neutral":"up"}>{trend.includes("concluir")?<ArrowDownRight/>:<ArrowUpRight/>}{trend}</em></div></article>)}</section><section className="dashboard-grid"><article className="panel revenue-panel"><PanelTitle title="Ingresos" subtitle="Últimos seis meses"/><div className="chart-total"><strong>$184,300</strong><span><ArrowUpRight/>12.4%</span></div><div className="bar-chart" aria-label="Gráfica de ingresos mensuales">{[["Abr",42],["May",55],["Jun",49],["Jul",67],["Ago",74],["Sep",88]].map(([m,h])=><div key={m}><span style={{height:`${h}%`}}/><small>{m}</small></div>)}</div></article><article className="panel treatments-chart"><PanelTitle title="Tratamientos" subtitle="Distribución este mes"/><div className="donut" aria-label="73 tratamientos activos"><span><strong>73</strong>activos</span></div><ul><li><i className="dot blue"/>Ortodoncia <b>31</b></li><li><i className="dot cyan"/>Implantes <b>18</b></li><li><i className="dot violet"/>Endodoncia <b>14</b></li><li><i className="dot gray"/>Otros <b>10</b></li></ul></article></section><section className="panel today-panel"><PanelTitle title="Próximas citas" subtitle="Agenda de hoy" action="Ver todas" to="/admin/appointments"/><AppointmentTable rows={initialAppointments.slice(0,5)}/></section></div></>}
export function AdminHeader({title,subtitle,action}){return <header className="admin-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</header>}
export function PanelTitle({title,subtitle,action,to="#"}){return <header className="panel-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{action&&<Link to={to}>{action}<ArrowRight/></Link>}</header>}
export function Status({value}){return <span className={`status status-${value.toLowerCase()}`}>{value}</span>}
export function AppointmentTable({rows,onStatus}){return <div className="table-scroll"><table><thead><tr><th>Paciente</th><th>Doctor</th><th>Tratamiento</th><th>Fecha</th><th>Hora</th><th>Estado</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.patient}</strong><small>{row.id}</small></td><td>{row.doctor}</td><td>{row.treatment}</td><td>{row.date}</td><td>{row.time}</td><td>{onStatus?<select aria-label={`Estado de ${row.patient}`} className={`status-select status-${row.status.toLowerCase()}`} value={row.status} onChange={e=>onStatus(row.id,e.target.value)}>{["Pendiente","Confirmada","Completada","Cancelada"].map(s=><option key={s}>{s}</option>)}</select>:<Status value={row.status}/>}</td></tr>)}</tbody></table></div>}
