import { test,expect } from "@playwright/test";
import { doctors,initialPatients,treatments } from "../src/data/clinic.js";
async function imagesLoad(page){for(const img of await page.locator("img").all()){await img.scrollIntoViewIfNeeded();await expect.poll(()=>img.evaluate(async el=>{await el.decode();return el.naturalWidth>0})).toBe(true)}}
async function login(page){await page.goto("/admin/login");await page.getByRole("button",{name:"Iniciar sesión"}).click();await expect(page).toHaveURL(/\/admin$/)}

test("sitio público: rutas, contenido, imágenes y consola",async({page})=>{const errors=[];const external=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>m.type()==="error"&&errors.push(m.text()));page.on("request",r=>{if(!r.url().startsWith("http://127.0.0.1:5177")&&!r.url().startsWith("data:"))external.push(r.url())});for(const route of["/","/treatments","/doctors","/appointments"]){await page.goto(route);await expect(page.locator("h1")).toBeVisible();await imagesLoad(page);const links=await page.locator("a[href]").evaluateAll(nodes=>nodes.map(n=>n.getAttribute("href")));expect(links.every(h=>h.startsWith("/")||h.startsWith("#"))).toBe(true)}expect(treatments).toHaveLength(6);expect(doctors).toHaveLength(4);await page.goto("/no-existe");await expect(page.locator("h1")).toContainText("no está en agenda");expect(errors).toEqual([]);expect(external).toEqual([])});

test("solicitud de cita valida y confirma sin enviar datos",async({page})=>{await page.goto("/appointments");await page.getByRole("button",{name:"Continuar"}).click();await expect(page.getByRole("alert")).toContainText("Selecciona");await page.getByLabel("Tratamiento").selectOption("cleaning");await page.getByLabel("Especialista").selectOption({label:"Dra. Elena Vargas"});await page.getByRole("button",{name:"Continuar"}).click();await page.getByLabel("Fecha").fill("2026-09-24");await page.getByRole("button",{name:"10:30"}).click();await page.getByRole("button",{name:"Continuar"}).click();await page.getByLabel("Nombre completo").fill("Andrea Fuentes");await page.getByLabel("Teléfono").fill("8188882233");await page.getByLabel("Correo electrónico").fill("andrea@correo.demo");await page.getByRole("button",{name:"Enviar solicitud"}).click();const dialog=page.getByRole("dialog");await expect(dialog).toContainText("Solicitud recibida");await expect(dialog).toContainText(/ND-\d{4}/);await expect(dialog).toContainText("No se envió información");await page.screenshot({path:"qa/appointment-confirmation.png"});await page.getByRole("button",{name:"Entendido"}).click();await expect(dialog).toHaveCount(0)});

test("login ficticio, protección de ruta y cierre de sesión",async({page})=>{await page.goto("/admin");await expect(page).toHaveURL(/\/admin\/login/);const password=page.getByRole("textbox",{name:/Contraseña/});await password.fill("incorrecta");await page.getByRole("button",{name:"Iniciar sesión"}).click();await expect(page.getByRole("alert")).toContainText("no coinciden");await password.fill("demo123");await page.getByRole("button",{name:"Iniciar sesión"}).click();await expect(page.getByRole("heading",{name:"Buenos días, Ana"})).toBeVisible();for(const value of["12","438","73","$184,300"])await expect(page.getByText(value,{exact:true}).first()).toBeVisible();await page.getByRole("button",{name:"Cerrar sesión"}).click();await expect(page).toHaveURL(/\/admin\/login/)});

test("estados de citas se guardan y pueden restablecerse",async({page})=>{await login(page);await page.goto("/admin/appointments");const state=page.getByLabel("Estado de Mariana Soto");await state.selectOption("Completada");await page.reload();await expect(page.getByLabel("Estado de Mariana Soto")).toHaveValue("Completada");page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Restablecer demo"}).click();await expect(page.getByLabel("Estado de Mariana Soto")).toHaveValue("Confirmada")});

test("CRUD de pacientes persiste crear, editar y eliminar",async({page})=>{expect(initialPatients).toHaveLength(15);await login(page);await page.goto("/admin/patients");await expect(page.locator("tbody tr")).toHaveCount(15);await page.getByRole("button",{name:"Nuevo paciente"}).click();const dialog=page.getByRole("dialog");await dialog.getByLabel("Nombre completo").fill("Valeria Campos");await dialog.getByLabel("Teléfono").fill("8111112222");await dialog.getByLabel("Edad").fill("32");await dialog.getByLabel("Correo electrónico").fill("valeria@correo.demo");await dialog.getByLabel("Última consulta").fill("2026-09-18");await dialog.getByRole("button",{name:"Guardar paciente"}).click();await expect(page.getByText("Valeria Campos")).toBeVisible();await page.reload();await expect(page.getByText("Valeria Campos")).toBeVisible();await page.getByRole("button",{name:"Editar a Valeria Campos"}).click();await page.getByRole("dialog").getByLabel("Nombre completo").fill("Valeria Campos Ruiz");await page.getByRole("button",{name:"Guardar paciente"}).click();await expect(page.getByText("Valeria Campos Ruiz")).toBeVisible();await page.getByRole("button",{name:"Eliminar a Valeria Campos Ruiz"}).click();await page.getByRole("button",{name:"Sí, eliminar"}).click();await expect(page.getByText("Valeria Campos Ruiz")).toHaveCount(0)});

test("filtros, directorios, configuración y empty state",async({page})=>{await login(page);await page.goto("/admin/patients");await page.getByLabel("Buscar pacientes").fill("no existe 999");await expect(page.getByText("No encontramos pacientes")).toBeVisible();await page.goto("/admin/treatments");await expect(page.locator(".directory-grid article")).toHaveCount(6);await page.goto("/admin/doctors");await expect(page.locator(".directory-grid article")).toHaveCount(4);await page.goto("/admin/settings");await page.getByRole("button",{name:"Guardar cambios"}).click();await expect(page.getByRole("status")).toContainText("guardadas")});

test("fallback de la fotografía conserva la portada",async({page})=>{await page.route("**/images/novadent-hero.png",r=>r.abort());await page.goto("/");await expect(page.locator(".hero-photo.picture-fallback")).toBeVisible();await expect(page.getByRole("heading",{name:/Tu sonrisa merece/})).toBeVisible()});

for(const width of[375,768,1440])test(`responsive público y admin ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});for(const route of["/","/treatments","/doctors","/appointments","/admin/login"]){await page.goto(route);await page.evaluate(()=>document.fonts.ready);await imagesLoad(page);const layout=await page.evaluate(()=>({path:location.pathname,scrollWidth:document.documentElement.scrollWidth,viewport:innerWidth}));expect(layout.scrollWidth,JSON.stringify(layout)).toBeLessThanOrEqual(width)}await page.goto("/");await page.screenshot({path:`qa/${width}-public.png`,fullPage:true});if(width===375){await page.getByRole("button",{name:"Abrir menú"}).click();await expect(page.getByRole("navigation",{name:"Navegación principal"})).toBeVisible()}await page.addInitScript(()=>localStorage.setItem("novadent_admin_session","demo"));await page.goto("/admin");expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`qa/${width}-admin.png`,fullPage:true});if(width<=760){await page.getByRole("button",{name:"Abrir menú"}).click();await expect(page.getByRole("navigation",{name:"Administración"})).toBeVisible()}});
