import { Link } from "react-router-dom";
import { ArrowRight, Check, HeartPulse, ShieldCheck, Sparkles } from "lucide-react";
import Picture from "../components/Picture";
import TreatmentCard from "../components/TreatmentCard";
import DoctorCard from "../components/DoctorCard";
import { doctors,treatments } from "../data/clinic";
export default function Home(){return <>
  <section className="clinic-hero"><Picture src="/images/novadent-hero.png" alt="Odontóloga explicando un tratamiento a un paciente" className="hero-photo"/><div className="hero-wash"/><div className="shell hero-copy"><span className="eyebrow">ODONTOLOGÍA CON SENTIDO HUMANO</span><h1>Tu sonrisa merece<br/><em>claridad y cuidado.</em></h1><p>Diagnósticos que entiendes, tratamientos que necesitas y un equipo que te acompaña en cada paso.</p><div className="hero-actions"><Link className="primary-button" to="/appointments">Agenda tu valoración <ArrowRight/></Link><Link className="text-link" to="/treatments">Conoce los tratamientos</Link></div><div className="hero-trust"><span><ShieldCheck/> Diagnóstico transparente</span><span><HeartPulse/> Atención sin prisas</span></div></div><div className="hero-note"><b>4.9</b><span>★★★★★<small>Más de 620 pacientes atendidos</small></span></div></section>
  <section className="care-strip"><div className="shell"><p>Todo comienza con una valoración completa.</p><span><Check/> Sin tratamientos innecesarios</span><span><Check/> Opciones y costos claros</span><span><Check/> Seguimiento personal</span></div></section>
  <section className="shell home-treatments"><div className="section-heading"><div><span className="eyebrow">CUIDADO INTEGRAL</span><h2>Una clínica para cada etapa de tu sonrisa.</h2></div><Link className="round-link" to="/treatments"><ArrowRight/><span>VER TODOS</span></Link></div><div className="treatments-grid">{treatments.slice(0,4).map((item,index)=><TreatmentCard key={item.id} item={item} index={index}/>)}</div></section>
  <section className="difference"><div className="difference-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="tooth-symbol" aria-hidden="true">N</span><div className="floating-pill pill-one"><Sparkles/> Tecnología de precisión</div><div className="floating-pill pill-two"><ShieldCheck/> Protocolos seguros</div></div><div className="difference-copy"><span className="eyebrow">UNA FORMA DISTINTA DE CUIDARTE</span><h2>Menos incertidumbre.<br/>Más confianza.</h2><p>Te mostramos qué vemos, explicamos cada alternativa y diseñamos contigo un plan realista. La tecnología nos ayuda a ser precisos; la conversación nos ayuda a cuidarte mejor.</p><div className="difference-stats"><span><strong>12+</strong>Años de experiencia</span><span><strong>96%</strong>Pacientes que nos recomiendan</span></div><Link className="light-button" to="/doctors">Conoce al equipo <ArrowRight/></Link></div></section>
  <section className="shell home-doctors"><div className="section-heading"><div><span className="eyebrow">EQUIPO CLÍNICO</span><h2>Especialistas que escuchan antes de tratar.</h2></div><p>Formación continua, criterios compartidos y una atención cercana.</p></div><div className="doctor-row">{doctors.slice(0,3).map(d=><DoctorCard key={d.id} doctor={d}/>)}</div></section>
  <section className="appointment-banner"><div><span>PRIMERA VISITA</span><h2>Empieza con una valoración clara.</h2><p>60 minutos para conocerte, revisar tu salud bucal y explicarte tus opciones.</p></div><Link to="/appointments">Agendar valoración <ArrowRight/></Link></section>
</>}
